//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("testModel", "city1_ibfk_1", "states", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcEntityframe.Models.state), "city1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcEntityframe.Models.city1), true)]
[assembly: EdmRelationshipAttribute("testModel", "userstate_ibfk_2", "city1", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcEntityframe.Models.city1), "userstate", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcEntityframe.Models.userstate), true)]
[assembly: EdmRelationshipAttribute("testModel", "userstate_ibfk_1", "states", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcEntityframe.Models.state), "userstate", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcEntityframe.Models.userstate), true)]

#endregion

namespace MvcEntityframe.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class testEntities3 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new testEntities3 object using the connection string found in the 'testEntities3' section of the application configuration file.
        /// </summary>
        public testEntities3() : base("name=testEntities3", "testEntities3")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new testEntities3 object.
        /// </summary>
        public testEntities3(string connectionString) : base(connectionString, "testEntities3")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new testEntities3 object.
        /// </summary>
        public testEntities3(EntityConnection connection) : base(connection, "testEntities3")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<city1> city1
        {
            get
            {
                if ((_city1 == null))
                {
                    _city1 = base.CreateObjectSet<city1>("city1");
                }
                return _city1;
            }
        }
        private ObjectSet<city1> _city1;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<state> states
        {
            get
            {
                if ((_states == null))
                {
                    _states = base.CreateObjectSet<state>("states");
                }
                return _states;
            }
        }
        private ObjectSet<state> _states;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<userstate> userstates
        {
            get
            {
                if ((_userstates == null))
                {
                    _userstates = base.CreateObjectSet<userstate>("userstates");
                }
                return _userstates;
            }
        }
        private ObjectSet<userstate> _userstates;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the city1 EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocity1(city1 city1)
        {
            base.AddObject("city1", city1);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the states EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTostates(state state)
        {
            base.AddObject("states", state);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the userstates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTouserstates(userstate userstate)
        {
            base.AddObject("userstates", userstate);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel", Name="city1")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class city1 : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new city1 object.
        /// </summary>
        /// <param name="cityid">Initial value of the cityid property.</param>
        /// <param name="cityname">Initial value of the cityname property.</param>
        /// <param name="stateid">Initial value of the stateid property.</param>
        public static city1 Createcity1(global::System.Int32 cityid, global::System.String cityname, global::System.Int32 stateid)
        {
            city1 city1 = new city1();
            city1.cityid = cityid;
            city1.cityname = cityname;
            city1.stateid = stateid;
            return city1;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cityid
        {
            get
            {
                return _cityid;
            }
            set
            {
                if (_cityid != value)
                {
                    OncityidChanging(value);
                    ReportPropertyChanging("cityid");
                    _cityid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("cityid");
                    OncityidChanged();
                }
            }
        }
        private global::System.Int32 _cityid;
        partial void OncityidChanging(global::System.Int32 value);
        partial void OncityidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cityname
        {
            get
            {
                return _cityname;
            }
            set
            {
                OncitynameChanging(value);
                ReportPropertyChanging("cityname");
                _cityname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cityname");
                OncitynameChanged();
            }
        }
        private global::System.String _cityname;
        partial void OncitynameChanging(global::System.String value);
        partial void OncitynameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 stateid
        {
            get
            {
                return _stateid;
            }
            set
            {
                OnstateidChanging(value);
                ReportPropertyChanging("stateid");
                _stateid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("stateid");
                OnstateidChanged();
            }
        }
        private global::System.Int32 _stateid;
        partial void OnstateidChanging(global::System.Int32 value);
        partial void OnstateidChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel", "city1_ibfk_1", "states")]
        public state state
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<state>("testModel.city1_ibfk_1", "states").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<state>("testModel.city1_ibfk_1", "states").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<state> stateReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<state>("testModel.city1_ibfk_1", "states");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<state>("testModel.city1_ibfk_1", "states", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel", "userstate_ibfk_2", "userstate")]
        public EntityCollection<userstate> userstates
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<userstate>("testModel.userstate_ibfk_2", "userstate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<userstate>("testModel.userstate_ibfk_2", "userstate", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel", Name="state")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class state : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new state object.
        /// </summary>
        /// <param name="stateid">Initial value of the stateid property.</param>
        /// <param name="statename">Initial value of the statename property.</param>
        public static state Createstate(global::System.Int32 stateid, global::System.String statename)
        {
            state state = new state();
            state.stateid = stateid;
            state.statename = statename;
            return state;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 stateid
        {
            get
            {
                return _stateid;
            }
            set
            {
                if (_stateid != value)
                {
                    OnstateidChanging(value);
                    ReportPropertyChanging("stateid");
                    _stateid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("stateid");
                    OnstateidChanged();
                }
            }
        }
        private global::System.Int32 _stateid;
        partial void OnstateidChanging(global::System.Int32 value);
        partial void OnstateidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String statename
        {
            get
            {
                return _statename;
            }
            set
            {
                OnstatenameChanging(value);
                ReportPropertyChanging("statename");
                _statename = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("statename");
                OnstatenameChanged();
            }
        }
        private global::System.String _statename;
        partial void OnstatenameChanging(global::System.String value);
        partial void OnstatenameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel", "city1_ibfk_1", "city1")]
        public EntityCollection<city1> city1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<city1>("testModel.city1_ibfk_1", "city1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<city1>("testModel.city1_ibfk_1", "city1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel", "userstate_ibfk_1", "userstate")]
        public EntityCollection<userstate> userstates
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<userstate>("testModel.userstate_ibfk_1", "userstate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<userstate>("testModel.userstate_ibfk_1", "userstate", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel", Name="userstate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class userstate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new userstate object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="firstname">Initial value of the firstname property.</param>
        /// <param name="lastname">Initial value of the lastname property.</param>
        /// <param name="email">Initial value of the email property.</param>
        /// <param name="address">Initial value of the address property.</param>
        /// <param name="stateid">Initial value of the stateid property.</param>
        /// <param name="cityid">Initial value of the cityid property.</param>
        /// <param name="number">Initial value of the number property.</param>
        public static userstate Createuserstate(global::System.Int32 id, global::System.String firstname, global::System.String lastname, global::System.String email, global::System.String address, global::System.Int32 stateid, global::System.Int32 cityid, global::System.String number)
        {
            userstate userstate = new userstate();
            userstate.id = id;
            userstate.firstname = firstname;
            userstate.lastname = lastname;
            userstate.email = email;
            userstate.address = address;
            userstate.stateid = stateid;
            userstate.cityid = cityid;
            userstate.number = number;
            return userstate;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String firstname
        {
            get
            {
                return _firstname;
            }
            set
            {
                OnfirstnameChanging(value);
                ReportPropertyChanging("firstname");
                _firstname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("firstname");
                OnfirstnameChanged();
            }
        }
        private global::System.String _firstname;
        partial void OnfirstnameChanging(global::System.String value);
        partial void OnfirstnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lastname
        {
            get
            {
                return _lastname;
            }
            set
            {
                OnlastnameChanging(value);
                ReportPropertyChanging("lastname");
                _lastname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("lastname");
                OnlastnameChanged();
            }
        }
        private global::System.String _lastname;
        partial void OnlastnameChanging(global::System.String value);
        partial void OnlastnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 stateid
        {
            get
            {
                return _stateid;
            }
            set
            {
                OnstateidChanging(value);
                ReportPropertyChanging("stateid");
                _stateid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("stateid");
                OnstateidChanged();
            }
        }
        private global::System.Int32 _stateid;
        partial void OnstateidChanging(global::System.Int32 value);
        partial void OnstateidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cityid
        {
            get
            {
                return _cityid;
            }
            set
            {
                OncityidChanging(value);
                ReportPropertyChanging("cityid");
                _cityid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cityid");
                OncityidChanged();
            }
        }
        private global::System.Int32 _cityid;
        partial void OncityidChanging(global::System.Int32 value);
        partial void OncityidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String number
        {
            get
            {
                return _number;
            }
            set
            {
                OnnumberChanging(value);
                ReportPropertyChanging("number");
                _number = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("number");
                OnnumberChanged();
            }
        }
        private global::System.String _number;
        partial void OnnumberChanging(global::System.String value);
        partial void OnnumberChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel", "userstate_ibfk_2", "city1")]
        public city1 city1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<city1>("testModel.userstate_ibfk_2", "city1").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<city1>("testModel.userstate_ibfk_2", "city1").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<city1> city1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<city1>("testModel.userstate_ibfk_2", "city1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<city1>("testModel.userstate_ibfk_2", "city1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel", "userstate_ibfk_1", "states")]
        public state state
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<state>("testModel.userstate_ibfk_1", "states").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<state>("testModel.userstate_ibfk_1", "states").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<state> stateReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<state>("testModel.userstate_ibfk_1", "states");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<state>("testModel.userstate_ibfk_1", "states", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
